// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import instance "bosh-linode-cpi/linode/instance_service"
import mock "github.com/stretchr/testify/mock"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CleanUp provides a mock function with given fields: id
func (_m *Service) CleanUp(id string) {
	_m.Called(id)
}

// Create provides a mock function with given fields: vmProps, registryEndpoint
func (_m *Service) Create(vmProps *instance.Properties, registryEndpoint string) (string, error) {
	ret := _m.Called(vmProps, registryEndpoint)

	var r0 string
	if rf, ok := ret.Get(0).(func(*instance.Properties, string) string); ok {
		r0 = rf(vmProps, registryEndpoint)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*instance.Properties, string) error); ok {
		r1 = rf(vmProps, registryEndpoint)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *Service) Delete(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
